### PR TITLE
Improvements to Linking with `pw-link` -- Moving to Link "Groups"

### PR DESCRIPTION
**Pull request by engineerjoe440**
## Changes

* I realized that there were some fundamentally incorrect assumptions in some of the previous work I'd provided in relation to the stereo links. This pull request addresses some of those incorrect interpretations of links to provide more meaningful representation.
* This removes "stereo" links and replaces them with links and link "groups," more appropriately representing the links as they are presented from the `pw-link` tooling.

### CODE REVIEW

**Comment by pablodz** [comment]
Is this ready to merge?

**Comment by engineerjoe440** [comment]
> Is this ready to merge?

Yep! Ready to merge! I may not have a chance to look at those failing build results until next week, though.

**Comment by pablodz** [comment]
I sent an invite to be a contrib, so you can merge anytime, check your email

**Comment by engineerjoe440** [comment]
> I sent an invite to be a contrib, so you can merge anytime, check your email

Awesome!!! Thank you, so much!

**Pull request merged**
